src/ejs/component/_c-new-label.ejs
src/ejs/index.ejs
src/package-lock.json
src/sass/object/component/_c-new-label.scss

c-new-label完成

---

src/ejs/component/_c-section-header__title.ejs
src/ejs/index.ejs
src/sass/object/component/_c-section-header__title.scss

c-section-header__title完成

---

src/ejs/common/_footer.ejs
src/sass/object/layout/_l-footer.scss
src/sass/object/project/_p-footer-nav.scss
src/sass/object/project/_p-footer.scss

c-logoを使用、footerの修正完成

---

src/ejs/index.ejs
src/ejs/project/_p-contact.ejs
src/sass/global/_setting.scss
src/sass/object/layout/_l-top-contact.scss
src/sass/object/project/_p-contact.scss
src/sass/object/project/_p-top-section-title.scss

btnのみ実装できてません。
コンポーネントとして完成してから追加します。
ご確認ください。

[add]contactを作成しました。

---

src/ejs/component/_c-pager.ejs
src/ejs/news.ejs
src/ejs/project/_p-news.ejs
src/ejs/project/_p-top-mv.ejs
src/sass/object/component/_c-pager.scss
src/sass/object/project/_p-news.scss

プラグインwppage-navを使用する前提でコーディングしております。

[add]下層ページに使用するpagerを作成しました。

---

src/ejs/index.ejs

[fix]セクション位置の調整

---

src/ejs/project/_p-lower-mv.ejs
src/ejs/project/_p-top-mv.ejs

to-topが反映されていなかったのでjsのコードを修正しました。
※ファイル名ですが、頭にfatureをつけておりましたが正しくはfixですね。

[fix]to-topのjs修正　

---

src/ejs/common/_head.ejs
src/ejs/project/_p-top-works.ejs
src/js/script.js
src/sass/object/project/_p-top-section-title.scss
src/sass/object/project/_p-top-works.scss

[update]worksの完成

---

src/js/script.js

[fix]to-top

---

src/js/script.js

スクロール後の背景変化の実装をしました。レビューお願いします。

[update]ヘッダーのスクロールアクションの実装

---

src/ejs/common/_p-header.ejs
src/ejs/project/_p-top-mv.ejs
src/sass/object/project/_p-header.scss

ロゴをh1ではなくdivに変更。ロゴのimgもaタグで囲んでindex.htmlに戻れるようにしました。
レビューお願いします。

[update]headerロゴの修正

---

src/ejs/common/_head.ejs
src/ejs/index.ejs
src/ejs/news.ejs
src/ejs/works.ejs

ページタイトルを変数化しました。レビューお願いします。
使用方法はindex.ejsの3行目をご確認ください。

[update]pageTitleの変数化

---

src/ejs/content.ejs
src/ejs/project/_p-content.ejs
src/sass/object/layout/_l-content.scss
src/sass/object/layout/_l-works.scss
src/sass/object/project/_p-content.scss
src/sass/object/project/_p-works.scss

[fix]下層ページのcontentとworksを変更

---

src/ejs/index.ejs
src/ejs/project/_p-contact.ejs
src/sass/object/project/_p-contact.scss

[update]p-contactをコンポーネントの中に記述

---

src/sass/object/component/_c-pager.scss

[fix]pager 変更

---

src/ejs/project/_p-card.ejs
src/ejs/project/_p-top-blog.ejs

[update]pathを変数化

---

src/sass/object/component/_c-pager.scss
src/sass/object/project/_p-blog-detail.scss

widthとheightを削除して、paddingで実装しました。

[fix]pager

---

src/ejs/blog-detail.ejs
src/ejs/blog.ejs
src/ejs/content.ejs
src/ejs/index.ejs
src/ejs/news.ejs
src/ejs/overview.ejs
src/ejs/project/_p-top-contact.ejs
src/ejs/works-detail.ejs
src/ejs/works.ejs
src/sass/object/layout/_l-top-contact.scss
src/sass/object/project/_p-top-contact.scss

[update]p-contactをp-top-contactに変更

---

src/ejs/contact-complete.ejs
src/ejs/project/_p-contact-complete.ejs
src/sass/object/layout/_l-contact-complete.scss
src/sass/object/project/_p-contact-complete.scss

[add]サンクスページ完成

---

src/sass/object/component/_c-new-label.scss

[update]不要なコードを削除

---

src/ejs/contact.ejs
src/ejs/project/_p-contact-form.ejs
src/sass/object/project/_p-contact-form.scss

-クラス名の混在の修正と
-オートフォーカス機能の追加
-ボタンにフォーカスが当たっているか視覚的に判断できるよう修正

[update]レビュー後のcontactページ修正
